"use client"

import { useRef, useState, useEffect } from "react"
import { motion, useScroll, useTransform } from "framer-motion"
import Image from "next/image"

const expCards = [
  {
    logoPath: "/amazon.jpg",
    company: "Amazon",
    title: "Software Development Engineer Intern",
    date: "May 2025- Present",
    responsibilities: [
      "In development..."
    ],
  },
  {
    logoPath: "/aims.png",
    company: "Artificial Intelligence and Multiphysics Simulations (AIMS) Lab",
    title: "Computing Group",
    date: "September 2024 - Present",
    responsibilities: [
      "Implementing an automated web scraping solution that extracted 120,000+ social media posts using a combination of keywords to prepare an analysis of the public sentiment towards U.S. clean nuclear energy transition using Playwright.",
      "Conducting sentiment analysis on the custom social media dataset by developing and training a multi-class sentiment classifier with DistilBERT, achieving a 92% accuracy using Support Vector Classifier",
      "Designing a user interface to display real-time sentiment statistics generated by the LLM, and integrating an automated data pipeline that dynamically updates the displayed statistics every hour based on newly collected social media interactions.",
    ],
  },
  {
    logoPath: "/mdst.jpeg",
    company: "Michigan Data Science Team (MDST)",
    title: "Data Analyst",
    date: "August 2023 - Present",
    responsibilities: [
      "Leveraged Pandas and NumPy to extract, clean, and preprocess 20,000+ data points on college football teams, ensuring data consistency through outlier detection, normalization, and handling missing values",
      "Conducted comprehensive Exploratory Data Analysis (EDA) using Matplotlib to uncover hidden offensive performance metrics that led to a 12% increase in model accuracy through effective feature engineering and parameter optimization.",
      "Developed a neural network using PyTorch to forecast a team's projected ranking, achieving an 88% testing accuracy and perfectly predicting the top 3 teams in the AP Top 25 rankings by tuning hyperparameters and regularization techniques.",
    ],
  },
]

const Experience = () => {
  const containerRef = useRef<HTMLDivElement>(null)
  const timelineRef = useRef<HTMLDivElement>(null)
  const [height, setHeight] = useState(0)

  useEffect(() => {
    if (containerRef.current) {
      const rect = containerRef.current.getBoundingClientRect()
      setHeight(rect.height)
    }
  }, [containerRef])

  const { scrollYProgress } = useScroll({
    target: containerRef,
    offset: ["start 20%", "end 80%"],
  })

  const heightTransform = useTransform(scrollYProgress, [0, 1], [0, height])
  const opacityTransform = useTransform(scrollYProgress, [0, 0.1], [0, 1])

  return (
    <section id="experience" className="flex justify-center items-center md:mt-40 mt-20 px-5 md:px-10 xl:px-0 w-full">
      <div className="w-full h-full md:px-20 px-5 mx-auto">
        <div className="flex flex-col items-center justify-center mb-20">
          <h1 className="heading z-20">My Experience</h1>
        </div>

        <div className="mt-16 relative" ref={containerRef}>
          <div
            className="absolute left-0 md:left-[120px] top-0 bottom-0 w-[2px] bg-[#1c1c21] z-10"
            ref={timelineRef}
            style={{ height: height + "px" }}
          />

          {/* <motion.div
            className="absolute left-0 md:left-[120px] top-0 w-[2px] bg-gradient-to-b from-[#6d45ce] via-[#fd5c79] to-[#62e0ff] z-20"
            style={{
              height: heightTransform,
              opacity: opacityTransform,
            }}
          /> */}

          <div className="relative z-30 space-y-16">
            {expCards.map((card, index) => (
              <div key={card.title} className="flex">
                <div className="relative mr-16 md:mr-32 flex-shrink-0">
                  <motion.div
                    initial={{ opacity: 0, scale: 0 }}
                    whileInView={{ opacity: 1, scale: 1 }}
                    viewport={{ amount: 0.5 }}
                    transition={{ duration: 0.5 }}
                    className="h-16 w-16 rounded-full z-40 relative overflow-hidden p-1 bg-white"
                  >
                    <Image
                      src={card.logoPath}
                      alt={`${card.company} logo`}
                      width={64}
                      height={64}
                      className="w-full h-full object-contain"
                      priority={index < 2}
                    />
                  </motion.div>
                </div>

                <motion.div
                  initial={{ opacity: 0, x: 50 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ amount: 0.3 }}
                  transition={{ duration: 0.8, ease: "easeOut" }}
                  className="flex-1 min-w-0"
                >
                  <h2 className="text-3xl md:text-4xl font-bold mb-3">{card.company}</h2>
                  <h3 className="text-xl md:text-2xl font-bold mb-3">{card.title}</h3>

                  <div className="flex items-center mb-6">
                    <div className="bg-[#1c1c21] px-3 py-1 rounded-sm inline-flex items-center">
                      <span className="mr-2">🗓️</span>
                      <span className="text-[#d9ecff]">{card.date}</span>
                    </div>
                  </div>

                  {/* resume-style bullet points here if desired */}
                  {/* <p className="text-[#839cb5] italic mb-6 text-lg">Responsibilities</p>
                  <ul className="space-y-6">
                    {card.responsibilities.map((responsibility, idx) => (
                      <li key={idx} className="flex items-start">
                        <span className="text-white mr-4 text-xl">•</span>
                        <span className="text-[#d9ecff] text-lg">{responsibility}</span>
                      </li>
                    ))}
                  </ul> */}
                </motion.div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  )
}

export default Experience